### ISSUE TITLE
一些建议以及感谢

### ISSUE THREAD

**Issue by BlademasterQAQ** [gitofleonardo/AnyDebug#13]
作者您好，

不知您是否听过 **Autojs** 项目，它目前仍在维护的地址：https://github.com/kkevsekk1/AutoX
这个项目是一个基于**Android无障碍**的自动化工具，可以通过图形交互界面快速定位所有的 View ，并获取其信息。（虽然其还存在一些问题，比如位于下层的View无法被选取，但是可以通过代码找到UI，并且可以通过悬浮窗非常方便的控制开关。）

我一直想实现一个能够修改View信息（如text）的root版Autojs，但是一直没有找到能够修改View信息的**开源项目**。直到今天发现您的这个项目，我才发现到我的想法是可能可以实现的，**非常感谢您无私的开源分享！**

看到您的其他issues，您貌似有让本项目的使用更加人性化的想法，希望 **Autojs** 项目能够帮助到您。

**Comment by gitofleonardo** [comment]
非常感谢你的建议，但是最近真的很忙，无暇再顾及其他事了，以后可能会重拾这个项目再来看看

**Comment by BlademasterQAQ** [comment]
> 非常感谢你的建议，但是最近真的很忙，无暇再顾及其他事了，以后可能会重拾这个项目再来看看

理解，主要是表达一下感谢，祝好！
