### ISSUE TITLE
1+9r  lsp 1.8.3 6552 magisk 25.1 闪退

### ISSUE THREAD

**Issue by 1a2b3clong** [gitofleonardo/AnyDebug#14]

**Comment by H3XDaemon** [comment]
同樣的問題
[crash_log.txt](https://github.com/gitofleonardo/AnyDebug/files/8958279/crash_log.txt)

**Comment by gitofleonardo** [comment]
服务注入失败，lsposed里面勾选系统框架了吗？

**Comment by 1a2b3clong** [comment]
噢噢，系统框架重启后就没闪退了
